language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
before_script:
  - sudo apt-get install pymetrics pychecker pylint pep8
  - pip install ordereddict coveralls
  - ./bootstrap install_dependencies
script: ./bootstrap -v && coverage run --source=src/main/python/pybuilder ./bootstrap run_unit_tests"
after_success:
  - coveralls --verbose
