language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

before_script:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - sudo apt-get install pymetrics pychecker pylint pep8
  - pip install coveralls
  - ./build.py install_dependencies -v

script:
  - ./build.py -v -X
  - PYTHONPATH=src/main/python coverage run --source=src/main/python build.py run_unit_tests -v
  - (cd target/dist/pybuilder-* && python setup.py install)

after_success:
  - coveralls --verbose
