language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"

before_script:
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm
  - pip install coveralls
  - ./build.py install_dependencies -v

script:
  - ./build.py -v -X
  - (cd target/dist/pybuilder-* && python setup.py install)

after_success:
  - coveralls --verbose
